export type FlagTypegenItem = {
  id: string;
  name: string;
  description?: string | null;
  enabled: boolean;
  schema: unknown;
};

export type TypegenResponse = {
  projectId: string;
  projectName?: string;
  flags: FlagTypegenItem[];
};

function isValidIdentifier(name: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}

export function jsonSchemaToTypeScript(schema: unknown, indent = 0): string {
  if (
    schema === true ||
    (typeof schema === "object" && schema !== null && Object.keys(schema).length === 0)
  ) {
    return "unknown";
  }
  if (!schema || typeof schema !== "object") {
    return "unknown";
  }

  const s = schema as Record<string, unknown>;

  if ("const" in s) {
    return JSON.stringify(s.const);
  }

  if (Array.isArray(s.enum)) {
    if (s.enum.length === 0) return "never";
    if (s.enum.length === 2 && s.enum.includes(true) && s.enum.includes(false)) {
      return "boolean";
    }
    return s.enum.map((val) => JSON.stringify(val)).join(" | ");
  }

  if (Array.isArray(s.anyOf)) {
    return s.anyOf.map((sub) => `(${jsonSchemaToTypeScript(sub, indent)})`).join(" | ");
  }

  if (Array.isArray(s.oneOf)) {
    return s.oneOf.map((sub) => `(${jsonSchemaToTypeScript(sub, indent)})`).join(" | ");
  }

  if (Array.isArray(s.allOf)) {
    return s.allOf.map((sub) => `(${jsonSchemaToTypeScript(sub, indent)})`).join(" & ");
  }

  const type = s.type;

  if (type === "string") {
    return "string";
  }
  if (type === "number" || type === "integer") {
    return "number";
  }
  if (type === "boolean") {
    return "boolean";
  }
  if (type === "null") {
    return "null";
  }

  if (type === "array") {
    if (s.items) {
      const itemType = jsonSchemaToTypeScript(s.items, indent);
      return `Array<${itemType}>`;
    }
    return "unknown[]";
  }

  if (type === "object" || s.properties) {
    const properties =
      s.properties && typeof s.properties === "object"
        ? (s.properties as Record<string, unknown>)
        : {};
    const requiredList = Array.isArray(s.required) ? (s.required as string[]) : [];
    const keys = Object.keys(properties);

    if (keys.length === 0) {
      if (s.additionalProperties) {
        return `Record<string, ${jsonSchemaToTypeScript(s.additionalProperties, indent)}>`;
      }
      return "Record<string, unknown>";
    }

    const pad = "  ".repeat(indent + 1);
    const closePad = "  ".repeat(indent);
    const lines = keys.map((key) => {
      const isReq = requiredList.includes(key);
      const opt = isReq ? "" : "?";
      const keyStr = isValidIdentifier(key) ? key : JSON.stringify(key);
      const valType = jsonSchemaToTypeScript(properties[key], indent + 1);
      return `${pad}${keyStr}${opt}: ${valType};`;
    });

    return `{\n${lines.join("\n")}\n${closePad}}`;
  }

  if (Array.isArray(type)) {
    return type.map((t) => jsonSchemaToTypeScript({ ...s, type: t }, indent)).join(" | ");
  }

  return "unknown";
}

export function generateTypeDeclarations(response: TypegenResponse): string {
  const flagLines = response.flags.map((flag) => {
    const docComment = flag.description
      ? `  /**\n   * ${flag.description.replace(/\n/g, "\n   * ")}\n   */\n`
      : "";
    const type = jsonSchemaToTypeScript(flag.schema, 1);
    const key = JSON.stringify(flag.name);
    return `${docComment}  ${key}: ${type};`;
  });

  return `/**
 * Auto-generated by @flaggable/sdk typegen.
 * Project: ${response.projectName || response.projectId} (${response.projectId})
 * Do not edit this file directly.
 */

export interface FlaggableGeneratedFlags {
${flagLines.join("\n\n")}
}

declare module "@flaggable/sdk" {
  export interface FlaggableFlags extends FlaggableGeneratedFlags {}
}

declare module "@flaggable/sdk/react" {
  export interface FlaggableFlags extends FlaggableGeneratedFlags {}
}

declare module "@flaggable/sdk/core" {
  export interface FlaggableFlags extends FlaggableGeneratedFlags {}
}
`;
}
